global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'discord-bot'
    static_configs:
      - targets: ['localhost:3894']  # Change selon ton port/API
        labels:
          service: 'soundshine-bot'
