# ========================================
# GitHub Actions CI/CD Pipeline
# ========================================

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize, closed]

# Permissions pour éviter les erreurs d'accès aux ressources
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: read

env:
  NODE_VERSION: "20"
  DOCKER_IMAGE: soundshine-bot

jobs:
  # Vérifier que la PR a été mergée (pour auto-deploy)
  check-merged:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    outputs:
      is-merged: ${{ steps.check.outputs.merged }}
    steps:
      - name: Check if PR was merged
        id: check
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "merged=true" >> $GITHUB_OUTPUT
          else
            echo "merged=false" >> $GITHUB_OUTPUT
          fi

  # Tests et qualité du code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  # Scan de sécurité
  security-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  # Auto-merge develop → main si tests OK (seulement si PR mergée)
  auto-merge:
    needs: [check-merged, test, security-code]
    if: |
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      needs.check-merged.outputs.is-merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge develop to main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          # Switch to main branch
          git checkout main
          git pull origin main

          # Merge develop into main
          git merge origin/develop --no-edit

          # Push to main
          git push origin main

          echo "✅ Successfully merged develop to main"

  # Déploiement automatique sur main (seulement si PR mergée)
  deploy:
    needs: [check-merged, test, security-code, auto-merge]
    if: |
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      needs.check-merged.outputs.is-merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Deploy commands
        run: npm run deploy:prod
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}

      - name: Notify Discord - Deploy Success
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: success
          title: "🚀 Déploiement Automatique"
          description: |
            ✅ Code mergé et déployé automatiquement !

            **PR:** ${{ github.event.pull_request.title }}
            **Auteur:** ${{ github.event.pull_request.user.login }}
            **Branche:** develop → main

  # Notifications générales (pour tous les événements)
  notify:
    runs-on: ubuntu-latest
    needs: [test, security-code]
    if: always() && github.event_name != 'pull_request'
    steps:
      - name: Notify Discord - Test Results
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: "🧪 Résultats des Tests"
          description: |
            ${{ job.status == 'success' && '✅ Tous les tests sont passés !' || '❌ Certains tests ont échoué.' }}

  # Notification d'échec général
  notify-failure:
    runs-on: ubuntu-latest
    needs: [test, security-code]
    if: failure()
    steps:
      - name: Notify Discord - Pipeline Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: failure
          title: "🚨 Échec du Pipeline CI/CD"
          description: "Le pipeline de déploiement a échoué"

  # Notification d'échec pour auto-deploy
  notify-deploy-failure:
    needs: [check-merged, test, security-code, auto-merge, deploy]
    if: failure() && github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord - Deploy Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: failure
          title: "❌ Échec Déploiement Auto"
          description: |
            Le déploiement automatique a échoué !

            **PR:** ${{ github.event.pull_request.title }}
            **Auteur:** ${{ github.event.pull_request.user.login }}

            Vérifiez les logs GitHub Actions.