# ========================================
# GitHub Actions CI/CD Pipeline
# ========================================

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

# Permissions pour éviter les erreurs d'accès aux ressources
permissions:
  contents: read
  security-events: write
  actions: read
  pull-requests: read

env:
  NODE_VERSION: "18"
  DOCKER_IMAGE: soundshine-bot

jobs:
  # Tests et qualité du code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  # Scan de sécurité
  security-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  # Notifications générales
  notify:
    runs-on: ubuntu-latest
    needs: [test, security-code]
    if: always()
    steps:
      - name: Notify Discord - Test Results
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: "🧪 Résultats des Tests"
          description: |
            ${{ job.status == 'success' && '✅ Tous les tests sont passés !' || '❌ Certains tests ont échoué.' }}

  # Notification d'échec
  notify-failure:
    runs-on: ubuntu-latest
    needs: [test, security-code]
    if: failure()
    steps:
      - name: Notify Discord - Pipeline Failure
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: failure
          title: "🚨 Échec du Pipeline CI/CD"
          description: "Le pipeline de déploiement a échoué"
